Thought.create content: "blah blah blah ipsum lorem"
Thought.create content: "blah blah second thought"
Thought.create content: "third thought blah blah blah ipsum lorem"
Thought.create content: "blah blah fourth thought blah ipsum lorem"
Thought.create content: "blah blah blah ipsum lorem fifth thought"
Thought.create content: "sixth thought blah blah blah ipsum lorem"
Thought.create content: "blah blah seventh thought blah ipsum lorem"
Thought.create content: "blah blah blah ipsum lorem eighth thought"
Thought.create content: "I have a dream"
Thought.create content: "You dream too much"
Thought.create content: "ipsum lorem blah blah blah ipsum lorem"
Thought.create content: "lorem blah blah another thought"
Thought.create content: "fumble thought blah blah blah ipsum lorem"
Thought.create content: "blah blah another thought blah ipsum lorem"
Thought.create content: "blah blah blah ipsum lorem filthy thought"
Thought.create content: "how many more thought blah blah blah ipsum lorem"
Thought.create content: "blah blah seventh thought blah ipsum lorem"
Thought.create content: "blah blah blah ipsum lorem almost done thought"
Thought.create content: "My fingers are sore"
Thought.create content: "get some Ben Gay"
